# This is a basic workflow to help you get started with Actions
#cool comment
# This is made Sergey Kon
name: My-GitHubActions-Basics

env:
   APPLICATION_NAME   : "MyFlask"
   DEPLOY_PACKAGE_NAME: "flask_deploy_ver_${{ github.sha }}"
   
# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  my_testing:
    
    runs-on: ubuntu-latest
    
    steps: 
    - name: Print Hello Message
      run : echo "Hello World from testing"
    - name: Execute few commands
      run : |
        echo "Hello message 1"
        echo "hello Message 2"
        echo "Application name: ${{env.APPLICATION_NAME}}"
    - name : List current folder
      run  : ls -la
  
  my_deploy: 
    runs-on: ubuntu-latest 
    needs: [my_testing]
    steps: 
    - name: Print Hello Message
      run : echo "Hello World from deploy"
    - name : Print Deployment Package
      run : |
          echo "Hello message 1"
          echo "hello Message 2"
          echo "Application name: ${{env.DEPLOY_PACKAGE_NAME}}"      
    
